apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: geolookup-maxmind
  namespace: geolookup
  labels:
    app.kubernetes.io/name: geolookupservice
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
