# Copy to a real secret or create with:
#   kubectl -n geolookup create secret generic geolookup-maxmind \
#     --from-literal=MAXMIND_ACCOUNT_ID='YOUR_ACCOUNT_ID' \
#     --from-literal=MAXMIND_LICENSE_KEY='YOUR_LICENSE_KEY'
# Never commit a real license key.
apiVersion: v1
kind: Secret
metadata:
  name: geolookup-maxmind
  namespace: geolookup
  labels:
    app.kubernetes.io/name: geolookupservice
type: Opaque
stringData:
  MAXMIND_ACCOUNT_ID: "REPLACE_ME"
  MAXMIND_LICENSE_KEY: "REPLACE_ME"
